import '@mantine/core/styles.css';
import { MantineProvider, ColorSchemeScript, Container, Title, Text } from '@mantine/core';
import type { Metadata } from 'next';
import { theme } from '@/theme';
import React from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout ({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="ja">
      <head>
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no" />
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <Container>
            <Title mt={'md'}>Create Next App</Title>
            <Title order={5} mb={'md'} c={'dimmed'}>物価上昇を耐え抜け</Title>
            {children}
          </Container>
        </MantineProvider>
      </body>
    </html>
  );
}
