import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { NextLink } from '@mantine/next';
import { Button, Container } from '@mantine/core';

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Hello index</h1>
      <Button component={NextLink} href="/page2">
      page2
      </Button>
    </Container>
  );
};

export default Home;
